### ISSUE TITLE
Error occurs when running with replaymod

### ISSUE THREAD

**Issue by Crystal0404** [badasintended/badpackets#13]
Minecraft Version:1.20.4
Fabric Version:0.15.3

This is my mod list:
```
badpackets-fabric-0.5.4.jar
replaymod-1.20.4-2.6.14.jar
```

log
```
[20:33:51] [main/INFO]: Loading Minecraft 1.20.4 with Fabric Loader 0.15.3
[20:33:52] [main/INFO]: Loading 11 mods:
	- badpackets 0.5.4
	- fabricloader 0.15.3
	   \-- mixinextras 0.3.2
	- java 17
	- minecraft 1.20.4
	- replaymod 1.20.4-2.6.14
	   |-- fabric-api-base 0.4.35+78d798af4f
	   |-- fabric-key-binding-api-v1 1.0.40+78d798af4f
	   |-- fabric-networking-api-v1 3.1.2+78d798af4f
	   |-- fabric-resource-loader-v0 0.11.15+78d798af4f
	   \-- fabric-screen-api-v1 2.0.16+78d798af4f
[20:33:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/D:/Game/minecraft/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:33:52] [main/INFO]: Compatibility level set to JAVA_16
[20:33:52] [main/INFO]: Compatibility level set to JAVA_17
[20:33:52] [main/WARN]: Reference map 'mixins.nonmmlauncher.replaymod.refmap.json' for mixins.nonmmlauncher.replaymod.json could not be read. If this is a development environment you can ignore this message
[20:33:52] [main/WARN]: Error loading class: net/optifine/render/ChunkVisibility (java.lang.ClassNotFoundException: net/optifine/render/ChunkVisibility)
[20:33:52] [main/WARN]: Error loading class: shadersmod/client/ShadersRender (java.lang.ClassNotFoundException: shadersmod/client/ShadersRender)
[20:33:52] [main/WARN]: Error loading class: net/optifine/shaders/ShadersRender (java.lang.ClassNotFoundException: net/optifine/shaders/ShadersRender)
[20:33:52] [main/WARN]: Error loading class: net/coderbot/iris/uniforms/CommonUniforms (java.lang.ClassNotFoundException: net/coderbot/iris/uniforms/CommonUniforms)
[20:33:52] [main/WARN]: Error loading class: net/coderbot/iris/Iris (java.lang.ClassNotFoundException: net/coderbot/iris/Iris)
[20:33:54] [main/INFO]: Initializing MixinExtras via com.llamalad7.mixinextras.service.MixinExtrasServiceImpl(version=0.3.2).
[20:33:57] [Datafixer Bootstrap/INFO]: 198 Datafixer optimizations took 134 milliseconds
[20:33:59] [Render thread/INFO]: Environment: Environment[sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[20:33:59] [Render thread/INFO]: Setting user: Crystal_0404
[20:34:00] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[20:34:01] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (fabric-api-base, fabric-key-binding-api-v1, fabric-networking-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabricloader, replaymod), replaymod_lang
[20:34:02] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[20:34:02] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[20:34:02] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[20:34:02] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_equip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_equip
[20:34:02] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_unequip1.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_unequip
[20:34:02] [Worker-Main-1/WARN]: File minecraft:sounds/mob/wolf/armor_unequip2.ogg does not exist, cannot add it to event minecraft:entity.wolf.armor_unequip
[20:34:02] [Worker-Main-12/INFO]: Found unifont_all_no_pua-15.1.04.hex, loading
[20:34:03] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[20:34:03] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[20:34:03] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on 扬声器 (Star Y360)
[20:34:03] [Render thread/INFO]: Sound engine started
[20:34:03] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[20:34:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[20:34:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[20:34:03] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[20:34:03] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[20:34:03] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[20:34:03] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[20:34:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[20:34:03] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[20:34:04] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[20:34:04] [Render thread/INFO]: Created: 512x256x0 minecraft:textures/atlas/particles.png-atlas
[20:34:04] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[20:34:04] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[20:34:04] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[20:34:07] [Render thread/WARN]: Missing data pack fabric
[20:34:08] [Render thread/INFO]: Loaded 7 recipes
[20:34:08] [Render thread/INFO]: Loaded 1271 advancements
[20:34:09] [Server thread/INFO]: Starting integrated minecraft server version 1.20.4
[20:34:09] [Server thread/INFO]: Generating keypair
[20:34:09] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:34:11] [Render thread/INFO]: 准备生成区域中：0%
[20:34:11] [Render thread/INFO]: 准备生成区域中：0%
[20:34:11] [Render thread/INFO]: 准备生成区域中：0%
[20:34:11] [Render thread/INFO]: 准备生成区域中：0%
[20:34:11] [Render thread/INFO]: 准备生成区域中：39%
[20:34:12] [Render thread/INFO]: Time elapsed: 2292 ms
[20:34:12] [Server thread/INFO]: Changing view distance to 12, from 10
[20:34:12] [Server thread/INFO]: Changing simulation distance to 12, from 0
[20:34:12] [Netty Local Client IO #0/INFO]: [System] [CHAT] [Replay Mod] 开始录制
[20:34:13] [Render thread/WARN]: Client disconnected with reason: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1) exceeds writerIndex(2): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 2, widx: 2, cap: 256)
[20:34:13] [Server thread/INFO]: com.mojang.authlib.GameProfile@3affeea2[id=d0d09afe-d6f8-4413-b213-48479153f103,name=Crystal_0404,properties={textures=[Property[name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTcwNDQ1ODAzODQ1MSwKICAicHJvZmlsZUlkIiA6ICJkMGQwOWFmZWQ2Zjg0NDEzYjIxMzQ4NDc5MTUzZjEwMyIsCiAgInByb2ZpbGVOYW1lIiA6ICJDcnlzdGFsXzA0MDQiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDg3MzczNDI3ZDc1MDk5YWZkNDQ4MGI3MGNhM2Y3ODc2NDFhOTNkYmM2Nzg5MGUwNmU2ZjU3ZTNmZWM2OWY5YSIsCiAgICAgICJtZXRhZGF0YSIgOiB7CiAgICAgICAgIm1vZGVsIiA6ICJzbGltIgogICAgICB9CiAgICB9LAogICAgIkNBUEUiIDogewogICAgICAidXJsIiA6ICJodHRwOi8vdGV4dHVyZXMubWluZWNyYWZ0Lm5ldC90ZXh0dXJlLzIzNDBjMGUwM2RkMjRhMTFiMTVhOGIzM2MyYTdlOWUzMmFiYjIwNTFiMjQ4MWQwYmE3ZGVmZDYzNWNhN2E5MzMiCiAgICB9CiAgfQp9, signature=iD0i/R/juiHiv6MuH9wyhF6avI/0XDlwSWGsItVBBQtzjCxGZwuqK5qtrKI4XBsSY3QYJo3s4Sb1DZH7tdPtldJrpfFSNltmjOX30QZZ//toA+IGDeroyrXrvAfvoJfujQ/AnKShB+zlazhfgENxeJn78ckQDbilGYFHkMa2KN6mU9ImP3ACKQvgHxJ3oHlh4Wtmpz+4g6GM7qvJx57KOesRPzfhKLagvSqmyZg1aEMoh4F8HaujHD8RxAdrdqO4bYQ2yheq4/sut2UDjo3QomQjn1ozj6fEqFrHfoFBrhby0avjrti/Ouw43B9GiaC0M4wT7GyniB2inKphxQ8YwH85lYp4vNy31jNKSBrmI8HFipO0efGPJbjHkvvA4n6KaIywN5NuJtbRg1AEZQ+79J9oyGiMIVLLRHQEn+pludiUVv8x9qQcwPoCo/hYpPkK2UECw1A1JDdrbbWDo4Uuz9mvD+JBFmncD0fYxNJlHmZfY0E2SIXqEoqUZdSwd0jzt5ZOJGNCP+PA7VtEenCFwjDtktwjqyNUvRfaesMJ4g5i7+f1pGNayp7V1sJTLjsS5J+t/7EkOqGjA26Y35S7XBRq2IG4ES7wxGFvDGeK3QrNPYJLhiOGkXp0WEZktkA/OYcKzdru82czz4tS+qzeittTiNVQCMt3i0TdSTbLljk=]]}] lost connection: 连接中断
[20:34:13] [Server thread/INFO]: Stopping singleplayer server as player logged out
[20:34:13] [Server thread/INFO]: Stopping server
[20:34:13] [Server thread/INFO]: Saving players
[20:34:13] [Server thread/INFO]: Saving worlds
[20:34:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:overworld
[20:34:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_nether
[20:34:14] [Server thread/INFO]: Saving chunks for level 'ServerLevel[新的世界]'/minecraft:the_end
[20:34:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (新的世界): All chunks are saved
[20:34:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:34:14] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:34:14] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[20:34:16] [Render thread/INFO]: Stopping!

```

I come from China, so there will be some Chinese characters in the log

**Comment by GLDYM** [comment]
A more detail log:
(Tweakermore appears but doesn't matter)
```
[11:14:26] [Netty Local Client IO #0/ERROR]: Packet error
java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1) exceeds writerIndex(2): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 2, widx: 2, cap: 256)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1442) ~[netty-buffer-4.1.97.Final.jar:?]
	at io.netty.buffer.AbstractByteBuf.readByte(AbstractByteBuf.java:730) ~[netty-buffer-4.1.97.Final.jar:?]
	at net.minecraft.class_2540.readByte(class_2540.java:1268) ~[client-intermediary.jar:?]
	at lol.bai.badpackets.impl.handler.AbstractPacketHandler.receiveChannelSyncPacket(AbstractPacketHandler.java:52) ~[badpackets-fabric-0.5.4.jar:?]
	at lol.bai.badpackets.impl.handler.AbstractPacketHandler.receive(AbstractPacketHandler.java:80) ~[badpackets-fabric-0.5.4.jar:?]
	at net.minecraft.class_8674.badpackets_handleCustomPayload(class_8674.java:1046) ~[client-intermediary.jar:?]
	at net.minecraft.class_8673.handler$zel000$badpackets$handleCustomPayload(class_8673.java:1028) ~[client-intermediary.jar:?]
	at net.minecraft.class_8673.method_52780(class_8673.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_53024(class_2658.java:94) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:32) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:196) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.redirect$fnm000$masa_gadget_mod-1_20_4$redirectGenericsFtw(class_2535.java:2706) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:181) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:60) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.dequeue(FlowControlHandler.java:202) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.channelRead(FlowControlHandler.java:164) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) ~[netty-codec-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelDelayer.lambda$channelRead$0(ChannelDelayer.java:42) ~[tweakermore-mc1.20.4-v3.15.1.jar:?]
	at me.fallenbreath.tweakermore.impl.mc_tweaks.connectionSimulatedDelay.ChannelDelayer.channelRead(ChannelDelayer.java:51) ~[tweakermore-mc1.20.4-v3.15.1.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.97.Final.jar:?]
	at com.replaymod.recording.packet.PacketListener$DecodedPacketListener.channelRead(PacketListener.java:562) ~[replaymod-1.20.4-2.6.14.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[netty-transport-4.1.97.Final.jar:?]
	at com.replaymod.recording.packet.PacketListener.channelRead(PacketListener.java:408) ~[replaymod-1.20.4-2.6.14.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:299) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.local.LocalChannel.doBeginRead(LocalChannel.java:322) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.beginRead(AbstractChannel.java:834) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.read(DefaultChannelPipeline.java:1362) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:835) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.handler.flow.FlowControlHandler.read(FlowControlHandler.java:144) ~[netty-handler-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeRead(AbstractChannelHandlerContext.java:837) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.read(AbstractChannelHandlerContext.java:814) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.read(DefaultChannelPipeline.java:1004) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannel.read(AbstractChannel.java:290) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.readIfIsAutoRead(DefaultChannelPipeline.java:1422) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelReadComplete(DefaultChannelPipeline.java:1417) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:482) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelReadComplete(AbstractChannelHandlerContext.java:463) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelReadComplete(DefaultChannelPipeline.java:925) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.local.LocalChannel.readInbound(LocalChannel.java:302) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.local.LocalChannel.finishPeerRead0(LocalChannel.java:445) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.local.LocalChannel.access$400(LocalChannel.java:50) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.channel.local.LocalChannel$5.run(LocalChannel.java:403) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.channel.DefaultEventLoop.run(DefaultEventLoop.java:54) ~[netty-transport-4.1.97.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.97.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.97.Final.jar:?]
	at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[11:14:26] [Render thread/INFO]: emissive suffixes loaded: {_e, _sbs}.
[11:14:26] [Render thread/WARN]: Client disconnected with reason: Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(2) + length(1) exceeds writerIndex(2): UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf(ridx: 2, widx: 2, cap: 256)
```
